### ISSUE TITLE
[Bug]: Exoskeleton upgrade information is missing in manual

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#341] opened 2024-09-11 19:29 UTC
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

~~I have installed Exoskeleton upgrade on LEA leggings. But when I start running, I still run with same speed as before. Charging the leggings doesn't change the situation at all.~~ Exoskeleton does work, but there is no information on pressing the key to activate it

### Side

Server

### Reproduction

~~1. Get/Craft LEA leggings~~
~~2. Get/Craft Exoskeleton upgrade~~
~~3. Apply Exoskeleton to leggings~~
~~4. Run~~
~~5. See that you don't get any boost in speed~~

### Expected Behaviour

~~When you run with exoskeleton leggings, your speed should be boosted~~ There must be information in manual on how to activate exoskeleton

### Other Evidence

![Image](https://github.com/user-attachments/assets/cc67f3b6-da54-4315-8855-2c7a020ccf32)

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by fastdelaspeed** [comment] 2024-09-12 13:06
This is not a bug, you haven't activated the leggings. It is not explained, but I believe the default keybind is "T." You press it and it will cycle between Off (default), On, and Overdrive (you will see an output in the chat). You should close the issue or change it into a request to include this info in the manual.

**Comment by LolscopeDev2022** [comment] 2024-09-12 13:29
> This is not a bug, you haven't activated the leggings. It is not explained, but I believe the default keybind is "T." You press it and it will cycle between Off (default), On, and Overdrive (you will see an output in the chat). You should close the issue or change it into a request to include this info in the manual.

1. Why T? T is a default key for opening the chat
2. Even with that, it doesn't work (no message or effect) even after pressing T (unbinded chat button for that) and every key on keyboard

So the issue remains

**Comment by fastdelaspeed** [comment] 2024-09-12 13:34
Sorry, i forgot i changed my binds. But please check the controls page (II controls are under Gameplay), there is a key that changes the legging mode. I asked about this issue months ago and was told the same thing in the Discord.

**Comment by LolscopeDev2022** [comment] 2024-09-12 15:02
> Sorry, i forgot i changed my binds. But please check the controls page (II controls are under Gameplay), there is a key that changes the legging mode. I asked about this issue months ago and was told the same thing in the Discord. Please also note that you need a capacitor backpack for the leggings to work.

Lol, actually it was tied to G (which was already taken by other mod). Other than that, the leggins actually work! Thanks, but I will instead reformate the issue to the addition of that information into manual.

**Comment by Pabilo8** [comment] 2024-09-13 20:25
@Avalon2106, add information for upgrade keybinds to the manual. 
Use `<keybind;key.immersiveintelligence.name>` to add a placeholder for the key instead of hardcoding them.
Keybinds are registered in ClientProxy.

**Closed** 2024-09-16 10:51 UTC
Labels: Bug
